dbgb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core import views as core_views
import pleio_auth

urlpatterns = [
    path('', include('pleio_auth.urls')),
    path('', core_views.home, name='home'),
    path('data', core_views.data, name='data'),
    path('data/<int:id>', core_views.data_detail, name='data_detail'),
    path('consumer', core_views.consumer, name='consumer'),
    path('consumer/<int:id>', core_views.consumer_detail, name='consumer_detail'),
    path('manage/consumer/<int:id>', core_views.manage_consumer, name='manage_consumer'),
    path('manage/consumer/<int:id>/data', core_views.manage_consumer_data, name='manage_consumer_data'),
    path('manage/consumer/<int:id>/data/new', core_views.manage_consumer_data_new, name='manage_consumer_data_new'),
    path('manage/consumer/<int:id>/data/<int:data_id>', core_views.manage_consumer_data_detail, name='manage_consumer_data_detail'),
    path('documents', core_views.documents, name='documents'),
    path('rules', core_views.rules, name='rules'),
    path('account', core_views.account, name='account'),
    path('admin/login/', pleio_auth.views.login, name='admin_login'),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth import get_user_model
import reversion
from datetime import datetime
from django.utils.translation import gettext_lazy as _

User = get_user_model()

def current_year():
    return datetime.now().year

class Cluster(models.Model):
    """Clustering data."""

    class Meta:
        ordering = ['name']

    name = models.CharField(max_length=140, unique=True)

    def __str__(self):
        return self.name

class ClusterInfo(models.Model):
    """Cluster information for each year."""

    class Meta:
        ordering = ['-year']

    cluster = models.ForeignKey(Cluster, on_delete=models.CASCADE, related_name='info')
    year = models.PositiveSmallIntegerField()
    information = models.TextField()
    conditions = models.TextField()

    def __str__(self):
        return '%s (%s)' % (self.data.name, self.year)

@reversion.register()
class Consumer(models.Model):
    """Consumer of data."""

    class Meta:
        ordering = ['fullname', 'name']
        verbose_name = 'afnemer'
        verbose_name_plural = 'afnemers'

    name = models.CharField(max_length=140, verbose_name="naam")
    fullname = models.CharField(default='', max_length=140, blank=True)
    description = models.TextField(verbose_name="omschrijving", blank=True)
    website = models.URLField(default='', blank=True)
    logo = models.ImageField(upload_to='logos', null=True, blank=True)
    year = models.PositiveSmallIntegerField(default=current_year, verbose_name="vanaf jaar")
    relation_number = models.IntegerField(null=True, blank=True, verbose_name="relatienummer")

    def __str__(self):
        if self.fullname:
            return self.fullname
        return self.name

    # Auto create default consumer info
    def update_relations(self):
        items = Data.objects.exclude(consumers__consumer=self)
        use = Use.objects.get(name="Onbekende code/aanpassen!")
        for data in items:
            DataConsumerInfo.objects.create(data=data, consumer=self, use=use)
    
class Data(models.Model):
    """Data base model."""

    class Meta:
        ordering = ['name']
        verbose_name = 'gegeven'
        verbose_name_plural = 'gegevens'

    name = models.CharField(max_length=140, unique=True)
    identification = models.CharField(default='', max_length=65)
    description = models.TextField()
    cluster = models.ForeignKey(Cluster, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.name

# Data information / year
class DataInfo(models.Model):
    """Data information for each year."""

    class Meta:
        ordering = ['-year']
        verbose_name = 'gegeven voor jaar'
        verbose_name_plural = 'gegevens voor jaar'

    data = models.ForeignKey(Data, on_delete=models.CASCADE, related_name='info')
    year = models.PositiveSmallIntegerField()
    information = models.TextField()
    format = models.CharField(default='', max_length=65)
    value_range = models.TextField()
    value_conditions = models.TextField()
    def __str__(self):
        return '%s (%s)' % (self.data.name, self.year)

class Use(models.Model):
    """Data consumer use types."""

    class Meta:
        verbose_name = 'gegeven gebruik'
        verbose_name_plural = 'gegevens gebruik'

    name = models.CharField(max_length=140, verbose_name="naam")
    def __str__(self):
        return "{0}: {1}".format(self.id, self.name)

class ConsequenceMissing(models.Model):
    """Data consumer consequence missing types."""
    class Meta:
        verbose_name = 'consequentie missen'
        verbose_name_plural = 'consequenties missen'

    name = models.CharField(max_length=140)
    def __str__(self):
        return "{0}: {1}".format(self.id, self.name)

@reversion.register()
class DataConsumerInfo(models.Model):
    """Data used by consumer."""

    class Meta:
        ordering = ['consumer__name', 'data__name']
        verbose_name = 'gegeven bij afnemer'
        verbose_name_plural = 'gegevens bij afnemer'
        unique_together = ("data", "consumer")

    data = models.ForeignKey(Data, on_delete=models.CASCADE, related_name='consumers', verbose_name="gegeven")
    consumer = models.ForeignKey(Consumer, on_delete=models.CASCADE, related_name='data', verbose_name="afnemer")
    use = models.ForeignKey(Use, on_delete=models.SET_NULL, blank=True, null=True, verbose_name="aanwending")
    use_text = models.TextField(default='', verbose_name="toelichting aanwending")
    consequence_missing = models.ForeignKey(ConsequenceMissing, on_delete=models.SET_NULL, blank=True, null=True, verbose_name="gevolg ontbreken")
    consequence_missing_text = models.TextField(default='', verbose_name="toelichting gevolg ontbreken")
    basis_use = models.TextField(default='', verbose_name="grondslag afname")
    def __str__(self):
        return '%s (%s)' % (self.data, self.consumer.name)

class Delivery(models.Model):
    """Consumer data delivery info."""

    class Meta:
        ordering = ['consumer__name', 'contract_type']
        verbose_name = 'levering'
        verbose_name_plural = 'lerveringen'

    consumer = models.ForeignKey(Consumer, on_delete=models.CASCADE, related_name='deliveries', verbose_name="afnemer")
    contract_type = models.CharField(max_length=140, verbose_name="contracttype")
    contract_number = models.CharField(max_length=140, verbose_name="contractnummer")
    delivery_type = models.CharField(max_length=140, verbose_name="soort levering")
    frequency = models.CharField(max_length=140, verbose_name="frequentie")

    def __str__(self):
        return '%s (%s)' % (self.contract_type, self.consumer.name)

class ConsumerUser(models.Model):
    """Consumer users."""

    class Meta:
        verbose_name = 'beheerder bij afnemer'
        verbose_name_plural = 'beheerders bij afnemer'
        unique_together = ("consumer", "user")
    
    consumer = models.ForeignKey(Consumer, on_delete=models.CASCADE, related_name='users', verbose_name="afnemer")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='consumers', verbose_name="beheerder")

    def __str__(self):
        return '%s (%s)' % (self.user.name, self.consumer.name)
    
class EventLog(models.Model):
    """Event log."""


    class Events(models.TextChoices):
        ACCESS_REQUEST_APPROVED = 'ACCESS_REQUEST_APPROVED', _('Access request approved')
        ACCESS_REQUEST_DENIED = 'ACCESS_REQUEST_DENIED', _('Access request denied')

    class Meta:
        ordering = ['-created']

    ip = models.GenericIPAddressField(null=True, blank=True, verbose_name="IP")
    userid = models.IntegerField(null=True, blank=True, default=0)
    email = models.CharField(max_length=255, null=True, blank=True)
    event_type = models.CharField(null=True, blank=True, max_length=255, choices=Events.choices)
    data = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s (%s)' % (self.event_type, self.email)
    
    def add_event(request, event_type, user=None, data=None):
        """Add event to log."""
        ip = request.session.get('ip', None)
        email = user.email if user else None
        userid = user.id if user else None
        EventLog.objects.create(ip=ip, userid=userid, email=email, event_type=event_type, data=data)

frontend/models.py
from django.db import models

# Create your models here.

frontend/views.py
from django.shortcuts import render

# Create your views here.

frontend/templates/503.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section class="section">
	<div class="container">
		<h2>Tijdelijk offline voor onderhoud</h2>
		<p>Database gegevensbelang zal in januari 2025 weer beschikbaar zijn.</p>
	</div>
</section>
{% endblock %}

frontend/templates/account.html
{% extends "base.html" %}
{% load static %}

{% block breadcrumb %}
<ul class="crumb">
	<li class="crumb__item"><a href="/" class="crumb__link">Home</a></li>
	<li class="crumb__item"><a href="/account" class="crumb__link">Account</a></li>
</ul>
{% endblock %}

{% block content %}
<article class="section">
	<div class="container">
		<h1>Account</h1>
		<p>De onderstaande PLEIO accountgegevens zijn bij ons bekend:</p>
		<p>
			Naam: {{ request.user.name }}<br>
			E-mail: {{ request.user.email }}<br>
			PLEIO-ID: {{ request.user.external_id }}
		</p>

		{% if consumers|length > 0 %}
			<h2>Afnemer Beheer</h2>
			<p>Je bent beheerder van één of meerdere afnemers. Klik op een afnemer om gegevens te wijzigen.</p>
			<ul>
			{% for item in consumers %}
				<li><a href="{% url 'manage_consumer' item.id %}">{{ item }}</a></li>
			{% endfor %}
		</ul>
		{% endif %}

		{% if request.user.is_admin %}
			<h2>Beheer</h2>
			<p>Je bent beheerder van deze applicatie. Via onderstaande link kan je naar de beheer omgeving.</p>
			<ul>
				<li><a href="/admin">Admin</a></li>
			</ul>
		{% endif %}

		<a href="/logout" class="btn btn-primary">Uitloggen</a>
	</div>
</article>
{% endblock %}

frontend/templates/base.html
{% load static %}
{% load render_bundle from webpack_loader %}
<!doctype html>
<html lang="nl">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
  	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Database Gegevensbelang 2025</title>
	<link rel="shortcut icon" href="{% static "favicon.ico" %}" type="image/x-icon"/>
	{% render_bundle 'app' 'css' %}
	<!-- Matomo -->
	<script type="text/javascript">
		var _paq = _paq || [];
		/* tracker methods like "setCustomDimension" should be called before "trackPageView" */
		_paq.push(['trackPageView']);
		_paq.push(['enableLinkTracking']);
		(function() {
			var u="https://stats.pleio.nl/";
			_paq.push(['setTrackerUrl', u+'piwik.php']);
			_paq.push(['setSiteId', '8013']);
			var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
			g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
		})();
	</script>
	<!-- End Matomo Code -->
</head>

<body>
	<header class="header">

		<div class="container header__top-container d-none d-sm-flex">
			<div class="header__logo">
				<a href="https://www.loonaangifteketen.nl/" class="header__logo-link" target="blank"><img src="{% static "images/logo-loonaangifteketen-desktop.svg" %}" alt="Loonaangifteketen" class="header__logo-img"></a>
			</div>
			<div class="header__brand">
				<a href="/" class="header__brand-link">Database Gegevensbelang 2025</a>
			</div>
		</div>

		<nav class="navbar navbar-dbgb navbar-dark bg-dark flex-md-nowrap navbar-expand-sm">
			<div class="container">
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav mr-auto nav-dbgb">
						<li class="nav-item  {% if request.resolver_match.url_name == 'home' %}active{% endif %}">
							<a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
						</li>
						{% if request.resolver_match.url_name != 'home' %}
						<li class="nav-item {% if 'data' in request.resolver_match.url_name %}active{% endif %}">
							<a class="nav-link" href="/data">Gegevens</a>
						</li>
						<li class="nav-item {% if 'consumer' in request.resolver_match.url_name %}active{% endif %}">
							<a class="nav-link" href="/consumer">Afnemers</a>
						</li>
						<li class="nav-item {% if request.resolver_match.url_name == 'documents' %}active{% endif %}">
							<a class="nav-link" href="/documents">Documenten</a>
						</li>
						{% endif %}
					</ul>

					<div class="header__top-menu">
						<ul class="navbar-nav">
							<li class="nav-item text-nowrap">
								{% if request.user.is_authenticated %}
								<a class="nav-link" href="/account">{{ request.user.name }}</a>
								{% else %}
								<a class="nav-link" href="/login">Inloggen</a>
								{% endif %}
							</li>
						</ul>
					</div>
				</div>
			</div>
		</nav>
	</header>

	<main role="main">
		{% if messages %}
		<div class="messages">
			{% for message in messages %}
			<div class="alert alert-info alert-dismissible fade show" role="alert">
				{{ message }}
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			{% endfor %}
		</div>
		{% endif %}
		{% block content %}{% endblock %}
	</main>

	<footer class="section section--navigation">
		<div class="container">
			{% block footer %}
			<div class="row justify-content-end">
				<div class="col-sm-3 ">
					<h3>Over deze site</h3>
					<a href="/rules" class="footer__link">Spelregels</a>
				</div>
			</div>
			{% endblock %}
		</div>
	</footer>

    <script>
		(function(d,t) {
		  var BASE_URL="http://localhost:3000";
		  var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
		  g.src=BASE_URL+"/packs/js/sdk.js";
		  g.defer = true;
		  g.async = true;
		  s.parentNode.insertBefore(g,s);
		  g.onload=function(){
			window.chatwootSDK.run({
			  websiteToken: 'VtJpQJT7m6Au9PRwT7Fpx2nz',
			  baseUrl: BASE_URL
			})
		  }
		})(document,"script");
	  </script>
	  
	{% render_bundle 'app' 'js' %}
</body>
</html>

frontend/templates/consumer.html
{% extends "base.html" %}
{% load static %}

{% block breadcrumb %}
<ul class="crumb">
	<li class="crumb__item"><a href="/" class="crumb__link">Home</a></li>
	<li class="crumb__item"><a href="/consumer" class="crumb__link">Afnemers</a></li>
	<li class="crumb__item is-active"><a href="{{ request.get_full_path }}" class="crumb__link">{{ consumer.name }}</a></li>
</ul>
{% endblock %}

{% block content %}
<article class="section">
	<div class="container">

		<div class="row">
			<div class="col-sm-8">
				<h1>
					{{ consumer }}
				</h1>
			</div>
			<div class="col-sm-4">
				{% if consumer.logo %}
				<img src="{{ consumer.logo.url }}" alt="{{ consumer.name }}" class="img-fluid" />
				{% endif %}
			</div>
		</div>

		<a class="btn btn-outline-secondary btn-sm mb-4" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
			Meer informatie
		</a>

		<div class="collapse" id="collapseExample">
			<div class="card card-body mb-4">
					{{ consumer.description|linebreaks }}
					<p>Website: <a href="{{ consumer.website }}" target="_blank">{{ consumer.website }}</a></p>
			</div>
		</div>

		<h3 class="mb-4 mt-4">Gebruik gegevens ({{ data|length }} in selectie)</h3>

		<div class="list-group list-group-flush mb-4">
		{% for item in data %}
			<a href="{% url 'data_detail' item.data.id %}" class="list-group-item list-group-item-action">{{ item.data.name }}</a>
		{% endfor %}
		</div>

		<h3 class="mb-4 mt-4">Levering</h3>
		{% if consumer.deliveries.all|length > 0 %}
			{% include "includes/delivery_table.html" with data=consumer.deliveries.all only %}
		{% else %}
			<p>-</p>
		{% endif %}

		<h3 class="mb-4 mt-4">Afnemer vanaf</h3>
		<p>{{ consumer.year }}</p>
	</div>
</article>
{% endblock%}

frontend/templates/consumer_list.html
{% extends "base.html" %}
{% load static %}

{% block breadcrumb %}
<ul class="crumb">
	<li class="crumb__item"><a href="/" class="crumb__link">Home</a></li>
	<li class="crumb__item is-active"><a href="/consumer" class="crumb__link">Afnemers</a></li>
</ul>
{% endblock %}

{% block content %}
<section class="section section--image">
	<div class="container"></div>
	<div class="section__bg-img" style="background-image: url({% static 'images/Afnemers_hor1600px.jpg' %})"></div>
</section>
<article class="section">
	<div class="container">
		<h1>Afnemers</h1>

		<div class="list-group list-group-flush">
		{% for item in consumers %}
			<a href="{% url 'consumer_detail' item.id %}" class="list-group-item list-group-item-action">
				{{ item }}
			</a>
		{% endfor %}
		</div>
	</div>
</article>
{% endblock%}

frontend/templates/data_search.html
{% extends "base.html" %}
{% load static %}

{% block breadcrumb %}
<ul class="crumb">
	<li class="crumb__item"><a href="/" class="crumb__link">Home</a></li>
	<li class="crumb__item is-active"><a href="/data" class="crumb__link">Gegevens</a></li>
</ul>
{% endblock %}

{% block content %}
<section class="section section--image">
	<div class="container"></div>
	<div class="section__bg-img" style="background-image: url({% static 'images/Gegevens_hor1600px.jpg' %})"></div>
</section>
<article class="section">
	<div class="container">
		<div class="row">
			<div class="col-sm-3 sidebar sidebar--main" id="search">
				<form method="GET" action="#search">
					<div class="form-group">
						<label for="q">{{ filter_form.q.label }}</label>
						{{ filter_form.q }}
					</div>

					<div class="form-group">
						<label for="cluster">{{ filter_form.cluster.label }}</label>
						{{ filter_form.cluster }}
					</div>

					<div class="form-group">
						<label for="year">{{ filter_form.year.label }}</label>
						{{ filter_form.year }}
					</div>

					<div class="form-group">
						<button type="submit" class="btn btn-primary btn-block">Filteren</button>
					</div>
				</form>
			</div>

			<div class="col-sm-9">
				<section class="section">
					{% if cluster_info %}
						<h2>{{ cluster_info.cluster.name }} ({{ data_selection|length }} in selectie)</h2>

						<h5>Condities voor de gehele gegevensgroep <a href="#conditionsModal" data-toggle="modal" data-target="#conditionsModal" class="icon icon--popup float--right"></a></h5>
						<div class="textarea mb-4">{{ cluster_info.conditions }}</div>

						<h5>Toelichting voor de (gehele) gegevensgroep <a href="#infoModal" data-toggle="modal" data-target="#infoModal" class="icon icon--popup float--right"></a></h5>
						<div class="textarea mb-4">{{ cluster_info.information }}</div>

					{% else %}
						<h2 class="mb-4">Gegevens ({{ data_selection|length }} in selectie)</h2>
					{% endif %}

					{% if data_selection|length > 0 %}
					<div class="list-group list-group-flush">
					{% for item in data_selection %}
						<a href="/data/{{ item.data.id }}" class="list-group-item list-group-item-action {% if selected.id == item.data.id %}active{% endif %}">{{ item.data.name }}</a>
					{% endfor %}
					</div>
					{% else %}
					<p>Geen gegevens gevonden met zoekterm "<strong>{{ filter_form.q.value }}</strong>" en cluster "<strong>{{ filter_form.cluster.value }}</strong>".</p>
					{% endif %}

					{% if cluster_info %}

					{% endif %}
				</section>
			</div>
		</div>
	</div>
</article>

{% if cluster_info %}
<div class="modal fade" id="conditionsModal" tabindex="-1" role="dialog" aria-labelledby="conditionsModal" aria-hidden="true">
	<div class="modal-dialog modal--full" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Condities voor de gehele gegevensgroep </h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
					<div class="textarea textarea--full">{{ cluster_info.conditions }}</div>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="infoModal" aria-hidden="true">
	<div class="modal-dialog modal--full" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Toelichting voor de (gehele) gegevensgroep</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
					<div class="textarea textarea--full">{{ cluster_info.information }}</div>
			</div>
		</div>
	</div>
</div>
{% endif %}
{% endblock %}

frontend/templates/manage_consumer.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block breadcrumb %}
<ul class="crumb">
	<li class="crumb__item"><a href="/" class="crumb__link">Home</a></li>
	<li class="crumb__item"><a href="/consumer" class="crumb__link">Afnemers</a></li>
	<li class="crumb__item is-active"><a href="{{ request.get_full_path }}" class="crumb__link">{{ consumer.name }}</a></li>
</ul>
{% endblock %}

{% block content %}
<article class="section">
	<div class="container">
		<form method="POST" enctype="multipart/form-data" novalidate>
			{% csrf_token %}

			{% for hidden_field in form.hidden_fields %}
				{{ hidden_field }}
			{% endfor %}

			<div class="row">
				<div class="col-sm-12">
					<h1>
						Beheer {{ consumer.name}}
					</h1>

					<p>In deze omgeving kunt u gegevens wijzigen van afnemer {{ consumer.name }}</p>
					
					{% include "includes/manage_menu.html" %}

					{% if form.non_field_errors %}
						<div class="alert alert-danger" role="alert">
							{% for error in form.non_field_errors %}
								{{ error }}
							{% endfor %}
						</div>
					{% endif %}

					{% for field in form.visible_fields %}

						{% if field.name != 'logo' %}
							<div class="form-group">
								{{ field.label_tag }}

								{% if form.is_bound %}
									{% if field.errors %}
										{% render_field field class="form-control is-invalid" %}
										{% for error in field.errors %}
											<div class="invalid-feedback">
												{{ error }}
											</div>
										{% endfor %}
									{% else %}
										{% render_field field class="form-control is-valid" %}
									{% endif %}
								{% else %}
									{% render_field field class="form-control" %}
								{% endif %}

								{% if field.help_text %}
									<small class="form-text text-muted">{{ field.help_text }}</small>
								{% endif %}
							</div>
						{% endif %}
					{% endfor %}
				</div>
			</div>

			<div class="row">
				<div class="col-sm-6">
					<div class="form-group">
						<div class="custom-file">
							{{ form.logo }}
							<label class="custom-file-label" for="id_logo">Kies een logo</label>
						</div>
						<small id="fileHelp" class="form-text text-muted">Je kan een .jpg of .png bestand selecteren als logo.</small>
					</div>
				</div>
				<div class="col-sm-6">
					{% if consumer.logo %}
						<img src="{{ consumer.logo.url }}" alt="{{ consumer.name }}" class="img-fluid" id="consumer_logo" />
					{% else %}
						<img src="{% static "images/no-logo.svg" %}" alt="Geen logo geselecteerd" class="img-fluid" id="consumer_logo" />
					{% endif %}
				</div>
			</div>

			<button class="btn btn-primary" type="submit">Wijzigingen opslaan</button>
		</form>
	</div>
</article>
{% endblock%}

frontend/templates/manage_consumer_data.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block breadcrumb %}
<ul class="crumb">
	<li class="crumb__item"><a href="/" class="crumb__link">Home</a></li>
	<li class="crumb__item"><a href="/consumer" class="crumb__link">Afnemers</a></li>
	<li class="crumb__item is-active"><a href="{{ request.get_full_path }}" class="crumb__link">{{ consumer.name }}</a></li>
</ul>
{% endblock %}

{% block content %}
<article class="section">
	<div class="container">

		<div class="row">
			<div class="col-sm-12">
				<h1>
					Beheer {{ consumer.name}}
				</h1>

				<p>In deze omgeving kunt u gegevens wijzigen van afnemer {{ consumer.name }}</p>

				{% include "includes/manage_menu.html" %}

				<div class="table-responsive">
					<p>Overzicht van afgenomen gegevens: klik op "bewerken" om de details te bekijken en/of aan te passen.</p>

					<table class="table">
					<thead>
						<tr>
							<th scope="col">Gegeven</th>
							<th scope="col">Aanwending</th>
							<th scope="col" colspan=2>Gevolg ontbreken</th>
						</tr>
					</thead>
					<tbody>
					{% for item in data %}
						<tr class="{% if item.use.id == 99 %}missing{% endif %}">
							<td scope="row">{{ item.data.name }}</td>
							<td>{{ item.use.name }}</td>
							<td>{{ item.consequence_missing.name }}</td>
							<td><a href="{% url 'manage_consumer_data_detail' consumer.id item.id %}" class="btn btn-outline-primary btn-sm">bewerken</button></td>
						</tr>
					{% endfor %}
					</tbody>
					</table>
				</div>


			</div>
		</div>

	</div>
</article>
{% endblock%}